/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

// Import Routes

import { Route as rootRoute } from './routes/__root';
import { Route as CallingImport } from './routes/calling';
import { Route as IndexImport } from './routes/index';

// Create/Update Routes

const CallingRoute = CallingImport.update({
	id: '/calling',
	path: '/calling',
	getParentRoute: () => rootRoute,
} as any);

const IndexRoute = IndexImport.update({
	id: '/',
	path: '/',
	getParentRoute: () => rootRoute,
} as any);

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
	interface FileRoutesByPath {
		'/': {
			id: '/';
			path: '/';
			fullPath: '/';
			preLoaderRoute: typeof IndexImport;
			parentRoute: typeof rootRoute;
		};
		'/calling': {
			id: '/calling';
			path: '/calling';
			fullPath: '/calling';
			preLoaderRoute: typeof CallingImport;
			parentRoute: typeof rootRoute;
		};
	}
}

// Create and export the route tree

export interface FileRoutesByFullPath {
	'/': typeof IndexRoute;
	'/calling': typeof CallingRoute;
}

export interface FileRoutesByTo {
	'/': typeof IndexRoute;
	'/calling': typeof CallingRoute;
}

export interface FileRoutesById {
	__root__: typeof rootRoute;
	'/': typeof IndexRoute;
	'/calling': typeof CallingRoute;
}

export interface FileRouteTypes {
	fileRoutesByFullPath: FileRoutesByFullPath;
	fullPaths: '/' | '/calling';
	fileRoutesByTo: FileRoutesByTo;
	to: '/' | '/calling';
	id: '__root__' | '/' | '/calling';
	fileRoutesById: FileRoutesById;
}

export interface RootRouteChildren {
	IndexRoute: typeof IndexRoute;
	CallingRoute: typeof CallingRoute;
}

const rootRouteChildren: RootRouteChildren = {
	IndexRoute: IndexRoute,
	CallingRoute: CallingRoute,
};

export const routeTree = rootRoute._addFileChildren(rootRouteChildren)._addFileTypes<FileRouteTypes>();

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/calling"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/calling": {
      "filePath": "calling.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
